/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

/**
 *
 * @author Usuario
 */
public class GUIMenuClient extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuClient
     */
    public GUIMenuClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtDescripComida = new javax.swing.JTextField();
        cbx_restaurante = new javax.swing.JComboBox<>();
        cbx_menu = new javax.swing.JComboBox<>();
        cbx_opcMenuDia = new javax.swing.JComboBox<>();
        txtListadoMenu = new javax.swing.JTextField();
        Btn_CerrarSesionClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Menu Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Seleccione el restaurante de su preferencia: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descripción de la comida: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Dirección:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Seleccione el menu: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 100, -1));
        getContentPane().add(txtDescripComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 60));

        cbx_restaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurante La Deliciosa", "Restaurante Quieta Margarita", "Restaurante Terra Inca" }));
        getContentPane().add(cbx_restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        cbx_menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menú del día", "Menú Especial" }));
        getContentPane().add(cbx_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        cbx_opcMenuDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Principio", "Proteina", "Bebida" }));
        getContentPane().add(cbx_opcMenuDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));
        getContentPane().add(txtListadoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, 90));

        Btn_CerrarSesionClient.setText("Cerrar Sesión");
        Btn_CerrarSesionClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarSesionClientActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_CerrarSesionClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CerrarSesionClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarSesionClientActionPerformed
        GUISelectorTipoUser guiInicio = new GUISelectorTipoUser();
        this.setVisible(false);
        guiInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_CerrarSesionClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CerrarSesionClient;
    private javax.swing.JComboBox<String> cbx_menu;
    private javax.swing.JComboBox<String> cbx_opcMenuDia;
    private javax.swing.JComboBox<String> cbx_restaurante;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDescripComida;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtListadoMenu;
    // End of variables declaration//GEN-END:variables

}
