/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.IClienteAccess;
import co.unicauca.microkernel.client.domain.ClienteService;
import co.unicauca.microkernel.common.entities.Component;
import co.unicauca.microkernel.common.entities.DayMenu;
import co.unicauca.microkernel.common.entities.Restaurant;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class GUIMenuClient extends javax.swing.JFrame {

    private IClienteAccess service;
    private ClienteService serviceRest;
    private Component componente;
    private DayMenu menu;
    private Restaurant restaurante;
    private String loginName;
    private List<Component> components;
    private List<Component> componentsMenu;
    String restName;
    String LoginAdmin;
    /**
     * Creates new form GUIMenuClient
     */
    public GUIMenuClient() {
        initComponents();
        restName= cbx_restaurante.getSelectedItem().toString();
        //LoginAdmin = RecuperarAdminRest(String restName);
    }
    private String RecuperarAdminRest(String restName){
        String Login;
        //necesito objeto restaurante
        //saco datos de ese objeto y los fijo en la caja de texto
        //saco el dato del userLoginName y lo retorno
        return "alonsito";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtDescripComida = new javax.swing.JTextField();
        Btn_CerrarSesionClient = new javax.swing.JButton();
        cbx_restaurante = new javax.swing.JComboBox<>();
        btnMenuDia = new javax.swing.JButton();
        btnMenuEspecial = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Seleccione el restaurante de su preferencia: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descripción de la comida: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Dirección:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Seleccione el menu: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 100, -1));
        getContentPane().add(txtDescripComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 60));

        Btn_CerrarSesionClient.setBackground(new java.awt.Color(0, 0, 255));
        Btn_CerrarSesionClient.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        Btn_CerrarSesionClient.setForeground(new java.awt.Color(255, 255, 255));
        Btn_CerrarSesionClient.setText("Cerrar Sesión");
        Btn_CerrarSesionClient.setBorder(null);
        Btn_CerrarSesionClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarSesionClientActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_CerrarSesionClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 130, 30));

        cbx_restaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurante La Deliciosa", "Restaurante Quieta Margarita", "Restaurante Terra Inca" }));
        getContentPane().add(cbx_restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        btnMenuDia.setBackground(new java.awt.Color(0, 0, 255));
        btnMenuDia.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnMenuDia.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuDia.setText("Menu Dia");
        btnMenuDia.setBorder(null);
        btnMenuDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuDiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 300, 120, 30));

        btnMenuEspecial.setBackground(new java.awt.Color(0, 0, 255));
        btnMenuEspecial.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnMenuEspecial.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuEspecial.setText("Menu Especial");
        btnMenuEspecial.setBorder(null);
        getContentPane().add(btnMenuEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CerrarSesionClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarSesionClientActionPerformed
        GUISelectorTipoUser guiInicio = new GUISelectorTipoUser();
        this.setVisible(false);
        guiInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_CerrarSesionClientActionPerformed

    private void btnMenuDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDiaActionPerformed
        GUIMostrarMenuDia guiMenu = new GUIMostrarMenuDia();
        this.setVisible(false);
        guiMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CerrarSesionClient;
    private javax.swing.JButton btnMenuDia;
    private javax.swing.JButton btnMenuEspecial;
    private javax.swing.JComboBox<String> cbx_restaurante;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDescripComida;
    private javax.swing.JTextField txtDireccion;
    // End of variables declaration//GEN-END:variables

}
