/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.Factory;
import co.unicauca.microkernel.client.access.IClienteAccess;
import co.unicauca.microkernel.client.domain.ClienteService;
import co.unicauca.microkernel.common.entities.User;
import co.unicauca.microkernel.core.domain.UserRepository;
import java.awt.Graphics;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class GUIRegistrarUsuario extends javax.swing.JFrame {

    private IClienteAccess service;
    private ClienteService serviceRest;
    private User usuario;
    
    //FondoPanel fondo =new FondoPanel();
    /** Creates new form GUIRegistrarUsuario */
    public GUIRegistrarUsuario() {
        service= Factory.getInstance().getClienteService();
        serviceRest= new ClienteService(service);
        this.usuario=new User();
        //this.setContentPane(fondo);
        initComponents();         
        //setLocationRelativeTo(null);
        //setSize(328, 399);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblUserLastName = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserLoginName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtUserLastName = new javax.swing.JTextField();
        txtUserEmail = new javax.swing.JTextField();
        txtUserMobile = new javax.swing.JTextField();
        txtUserAddress = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        btnRegistarUsuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbx_tipoUser = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Btn_Atras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setForeground(new java.awt.Color(153, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("Nombre(s):* ");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lblUserLastName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUserLastName.setText("Apellido:*");
        getContentPane().add(lblUserLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lblUserEmail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUserEmail.setText("E-mail:*");
        getContentPane().add(lblUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Teléfono:* (+57)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Dirección:* ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Login:*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Contraseña:*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(txtUserLoginName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 119, -1));
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 119, -1));
        getContentPane().add(txtUserLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 119, -1));
        getContentPane().add(txtUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 119, -1));
        getContentPane().add(txtUserMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 119, -1));
        getContentPane().add(txtUserAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 119, -1));
        getContentPane().add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 119, -1));

        btnRegistarUsuario.setBackground(new java.awt.Color(0, 0, 255));
        btnRegistarUsuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnRegistarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistarUsuario.setText("Registrarse");
        btnRegistarUsuario.setBorder(null);
        btnRegistarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 110, 30));

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Registro de Usuario");
        jLabel6.setDoubleBuffered(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        cbx_tipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "cliente" }));
        getContentPane().add(cbx_tipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 110, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Tipo Usuario:*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        Btn_Atras.setBackground(new java.awt.Color(0, 0, 255));
        Btn_Atras.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        Btn_Atras.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Atras.setText("<----");
        Btn_Atras.setToolTipText("retroceder una pagina");
        Btn_Atras.setAutoscrolls(true);
        Btn_Atras.setBorder(null);
        Btn_Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 60, 30));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarUsuarioActionPerformed
        usuario.setUserLoginName(txtUserLoginName.getText());
        usuario.setUserPassword(txtUserPassword.getText());
        usuario.setUserName(txtUserName.getText());
        usuario.setUserLastName(txtUserLastName.getText());
        usuario.setUserAddres(txtUserAddress.getText());
        usuario.setUserMobile(txtUserMobile.getText());
        usuario.setUserEmail(txtUserEmail.getText());
        usuario.setUserType(cbx_tipoUser.getSelectedItem().toString());
                    
            String varLogin;
            String usuarioCreado;
        try {
            //se verifica si el login ya existe en el sistema
            varLogin = serviceRest.findUser(txtUserLoginName.getText());
                        
            if(varLogin!="Fallo"){//si el login se encuentra en el sistema                
                JOptionPane.showMessageDialog(null, "El Login ya existe, cambielo para que pueda registrarse");                                
            }else{
                //se manda a crear el usuario
                usuarioCreado = serviceRest.createUser(usuario);
                if (usuarioCreado!= "Fallo crear usuario") {//Si no se presento inconveniente en su creación
                 JOptionPane.showMessageDialog(null, "Ha sido creado el usuario ");           
                } 
            }
                    
        
        } catch (Exception ex) {
            Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistarUsuarioActionPerformed

    private void Btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AtrasActionPerformed
        GUISelectorTipoUser guiPrincipal = new GUISelectorTipoUser();
        this.setVisible(false);
        guiPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_AtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Atras;
    private javax.swing.JButton btnRegistarUsuario;
    private javax.swing.JComboBox<String> cbx_tipoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserLastName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtUserAddress;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserLastName;
    private javax.swing.JTextField txtUserLoginName;
    private javax.swing.JTextField txtUserMobile;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagen/img_FondoRegistroUsuario.jpg")).getImage();
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
